# Question answering on the SQuAD dataset

In [211]:
import sys
import random
from functools import partial

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
import wandb
import transformers
import tokenizers

from tokenizers import Tokenizer
from tokenizers.models import WordLevel
from tokenizers.normalizers import Sequence, StripAccents, Lowercase, Strip
from tokenizers.pre_tokenizers import Sequence as PreSequence
from tokenizers.pre_tokenizers import Whitespace, Punctuation
from tokenizers import BertWordPieceTokenizer

import dataset
import model
import training
import utils

%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
plt.rcParams['figure.figsize'] = [8, 6]
plt.rcParams['figure.dpi'] = 100
plt.rcParams['axes.xmargin'] = .05
plt.rcParams['axes.ymargin'] = .05
plt.style.use('ggplot')

In [3]:
WANDB_PROJECT = "squad-qa"
WANDB_ENTITY = "wadaboa"
WANDB_MODE = "online"
WANDB_RESUME = "never"

init_wandb = partial(
    wandb.init,
    project=WANDB_PROJECT,
    entity=WANDB_ENTITY,
    mode=WANDB_MODE,
    resume=WANDB_RESUME,
)

## Preliminaries

### Raw data loading

In [4]:
squad_dataset = dataset.SquadDataset()

In [5]:
squad_dataset.raw_train_df

question_id  \
0      5733be284776f41900661182   
1      5733be284776f4190066117f   
2      5733be284776f41900661180   
3      5733be284776f41900661181   
4      5733be284776f4190066117e   
...                         ...   
87594  5735d259012e2f140011a09d   
87595  5735d259012e2f140011a09e   
87596  5735d259012e2f140011a09f   
87597  5735d259012e2f140011a0a0   
87598  5735d259012e2f140011a0a1   

                                                question  \
0      To whom did the Virgin Mary allegedly appear i...   
1      What is in front of the Notre Dame Main Building?   
2      The Basilica of the Sacred heart at Notre Dame...   
3                      What is the Grotto at Notre Dame?   
4      What sits on top of the Main Building at Notre...   
...                                                  ...   
87594  In what US state did Kathmandu first establish...   
87595               What was Yangon previously known as?   
87596  With what Belorussian city does Kathmandu have...   
87597  In what year did Kathmandu create its initial ...   
87598                      What is KMC an initialism of?   

                          title  context_id  \
0      University_of_Notre_Dame           0   
1      University_of_Notre_Dame           0   
2      University_of_Notre_Dame           0   
3      University_of_Notre_Dame           0   
4      University_of_Notre_Dame           0   
...                         ...         ...   
87594                 Kathmandu       18890   
87595                 Kathmandu       18890   
87596                 Kathmandu       18890   
87597                 Kathmandu       18890   
87598                 Kathmandu       18890   

                                                 context  \
0      Architecturally, the school has a Catholic cha...   
1      Architecturally, the school has a Catholic cha...   
2      Architecturally, the school has a Catholic cha...   
3      Architecturally, the school has a Catholic cha...   
4      Architecturally, the school has a Catholic cha...   
...                                                  ...   
87594  Kathmandu Metropolitan City (KMC), in order to...   
87595  Kathmandu Metropolitan City (KMC), in order to...   
87596  Kathmandu Metropolitan City (KMC), in order to...   
87597  Kathmandu Metropolitan City (KMC), in order to...   
87598  Kathmandu Metropolitan City (KMC), in order to...   

                                        answer  answer_start  answer_end  
0                   Saint Bernadette Soubirous           515         541  
1                    a copper statue of Christ           188         213  
2                            the Main Building           279         296  
3      a Marian place of prayer and reflection           381         420  
4           a golden statue of the Virgin Mary            92         126  
...                                        ...           ...         ...  
87594                                   Oregon           229         235  
87595                                  Rangoon           414         421  
87596                                    Minsk           476         481  
87597                                     1975           199         203  
87598              Kathmandu Metropolitan City             0          27  

[87599 rows x 8 columns]

In [6]:
squad_dataset.raw_test_df

question_id  \
0      56be4db0acb8001400a502ec   
1      56be4db0acb8001400a502ed   
2      56be4db0acb8001400a502ee   
3      56be4db0acb8001400a502ee   
4      56be4db0acb8001400a502ee   
...                         ...   
18211  5737aafd1c456719005744fd   
18212  5737aafd1c456719005744fd   
18213  5737aafd1c456719005744fd   
18214  5737aafd1c456719005744fe   
18215  5737aafd1c456719005744ff   

                                                question          title  \
0      Which NFL team represented the AFC at Super Bo...  Super_Bowl_50   
1      Which NFL team represented the NFC at Super Bo...  Super_Bowl_50   
2                    Where did Super Bowl 50 take place?  Super_Bowl_50   
3                    Where did Super Bowl 50 take place?  Super_Bowl_50   
4                    Where did Super Bowl 50 take place?  Super_Bowl_50   
...                                                  ...            ...   
18211  What is a very seldom used unit of mass in the...          Force   
18212  What is a very seldom used unit of mass in the...          Force   
18213  What is a very seldom used unit of mass in the...          Force   
18214  What seldom used term of a unit of force equal...          Force   
18215  What is the seldom used force unit equal to on...          Force   

       context_id                                            context  \
0               0  Super Bowl 50 was an American football game to...   
1               0  Super Bowl 50 was an American football game to...   
2               0  Super Bowl 50 was an American football game to...   
3               0  Super Bowl 50 was an American football game to...   
4               0  Super Bowl 50 was an American football game to...   
...           ...                                                ...   
18211        2066  The pound-force has a metric counterpart, less...   
18212        2066  The pound-force has a metric counterpart, less...   
18213        2066  The pound-force has a metric counterpart, less...   
18214        2066  The pound-force has a metric counterpart, less...   
18215        2066  The pound-force has a metric counterpart, less...   

                                                  answer  answer_start  \
0                                         Denver Broncos           177   
1                                      Carolina Panthers           249   
2                                Santa Clara, California           403   
3                                         Levi's Stadium           355   
4      Levi's Stadium in the San Francisco Bay Area a...           355   
...                                                  ...           ...   
18211                                               slug           274   
18212                                        metric slug           267   
18213                                    the metric slug           263   
18214                                                kip           712   
18215                                             sthène           665   

       answer_end  
0             191  
1             266  
2             426  
3             369  
4             427  
...           ...  
18211         278  
18212         278  
18213         278  
18214         715  
18215         671  

[18216 rows x 8 columns]

### Embeddings

In [7]:
UNK_TOKEN = "[UNK]"
PAD_TOKEN = "[PAD]"

- FastText: 
    - _fasttext-wiki-news-subwords_ (dimensions: 300)
- GloVe:
    - _glove-twitter_ (dimensions: 25. 50, 100, 200)
    - _glove-wiki-gigaword_ (dimensions: 50, 100, 200, 300)
- Word2Vec:
    - _word2vec-google-news_ (dimensions: 300)
    - _word2vec-ruscorpora_ (dimensions: 300)

In [8]:
# See https://github.com/RaRe-Technologies/gensim-data
GLOVE_EMBEDDING_DIMENSION = 50
GLOVE_MODEL_NAME = "glove-twitter"
glove_embedding_model = utils.load_embedding_model(
    GLOVE_MODEL_NAME, embedding_dimension=GLOVE_EMBEDDING_DIMENSION
)

In [9]:
glove_unk = np.mean(glove_embedding_model.vectors, axis=0)
glove_embedding_model.add(UNK_TOKEN, glove_unk)

In [10]:
glove_embedding_model[UNK_TOKEN]

array([-0.21896735,  0.17269313, -0.05617283,  0.06307325,  0.00960657,
       -0.23461065, -0.16731773, -0.25613925,  0.12990713, -0.34179848,
       -0.07411992,  0.00533567,  0.7090377 , -0.1139018 ,  0.10613882,
        0.09186497,  0.15880948,  0.03158554,  0.2241412 ,  0.20387109,
        0.05305386,  0.04961218,  0.11807557, -0.10199773, -0.18345806,
        0.56560194,  0.07183363,  0.04322447, -0.39442873,  0.06828266,
        0.39542177,  0.08794834,  0.41605434, -0.27820984, -0.5106833 ,
       -0.16443801,  0.0973425 ,  0.02233286,  0.19346187,  0.15909852,
        0.886585  , -0.01498107,  0.10211241, -0.12959567, -0.328366  ,
        0.13014658, -0.02061043,  0.05735753,  0.14008364,  0.22588447],
      dtype=float32)

In [11]:
list(glove_embedding_model.vocab.keys())[-1]

'[UNK]'

In [12]:
any(np.all(glove_embedding_model.vectors == 0, axis=1))

False

In [13]:
glove_embedding_model.add(PAD_TOKEN, np.zeros((1, GLOVE_EMBEDDING_DIMENSION)))
glove_embedding_model[PAD_TOKEN]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [14]:
list(glove_embedding_model.vocab.keys())[-1]

'[PAD]'

In [15]:
glove_embedding_model.vectors.shape

(1193516, 50)

In [16]:
glove_vocab = dict(
    zip(glove_embedding_model.index2word, range(len(glove_embedding_model.index2word)))
)

In [17]:
glove_embedding_layer = nn.Embedding(
    glove_embedding_model.vectors.shape[0],
    GLOVE_EMBEDDING_DIMENSION,
    padding_idx=glove_vocab[PAD_TOKEN],
)
glove_embedding_layer.weight = nn.Parameter(
    torch.from_numpy(glove_embedding_model.vectors)
)
glove_embedding_layer.weight.requires_grad = False

### Standard tokenizer and preprocessing

In [18]:
MAX_CONTEXT_TOKENS = 300

In [351]:
standard_question_tokenizer = Tokenizer(WordLevel(glove_vocab, unk_token=UNK_TOKEN))
standard_question_tokenizer.normalizer = Sequence(
    [StripAccents(), Lowercase(), Strip()]
)
standard_question_tokenizer.pre_tokenizer = PreSequence([Whitespace(), Punctuation()])
standard_question_tokenizer.enable_padding(
    direction="right", pad_id=glove_vocab[PAD_TOKEN], pad_type_id=1, pad_token=PAD_TOKEN
)

standard_context_tokenizer = Tokenizer(WordLevel(glove_vocab, unk_token=UNK_TOKEN))
standard_context_tokenizer.normalizer = Sequence([StripAccents(), Lowercase(), Strip()])
standard_context_tokenizer.pre_tokenizer = PreSequence([Whitespace(), Punctuation()])
standard_context_tokenizer.enable_padding(
    direction="right",
    pad_id=glove_vocab[PAD_TOKEN],
    pad_type_id=1,
    pad_token=PAD_TOKEN,
    length=MAX_CONTEXT_TOKENS,
)
standard_context_tokenizer.enable_truncation(MAX_CONTEXT_TOKENS)

In [352]:
standard_tokenizer = dataset.StandardSquadTokenizer(
    standard_question_tokenizer, standard_context_tokenizer
)

In [353]:
standard_dm = dataset.SquadDataManager(squad_dataset, standard_tokenizer)

In [354]:
standard_dm.train_df

question_id  \
0      56cc239e6d243a140015eeb7   
1      56cc27346d243a140015eeba   
2      56cc27346d243a140015eebb   
3      56cc27346d243a140015eebc   
4      56cc27346d243a140015eebd   
...                         ...   
69864  573636bf9c79961900ff7e06   
69865  573636bf9c79961900ff7e07   
69866  573636bf9c79961900ff7e08   
69867  573636bf9c79961900ff7e09   
69868  573636bf9c79961900ff7e0a   

                                                question  \
0              Who were Wang Jiawei and Nyima Gyaincain?   
1      What important trade did the Ming Dynasty have...   
2      During what years did the Mongol leader Kublai...   
3      Who did the Yongle Emperor try to build a reli...   
4             Deshin Shekpa was the head of what school?   
...                                                  ...   
69864           What Botswana was resently forced to do?   
69865              What animal declined across Botswana?   
69866    What animal numbers have increased in Botswana?   
69867     What animal numbers remain stable in Botswana?   
69868  What else is partly to blame for the declining...   

                                                title  context_id  \
0      Sino-Tibetan_relations_during_the_Ming_dynasty         299   
1      Sino-Tibetan_relations_during_the_Ming_dynasty         300   
2      Sino-Tibetan_relations_during_the_Ming_dynasty         300   
3      Sino-Tibetan_relations_during_the_Ming_dynasty         300   
4      Sino-Tibetan_relations_during_the_Ming_dynasty         300   
...                                               ...         ...   
69864                                         Hunting       18832   
69865                                         Hunting       18832   
69866                                         Hunting       18832   
69867                                         Hunting       18832   
69868                                         Hunting       18832   

                                                 context  \
0      The exact nature of relations between Tibet an...   
1      Some scholars note that Tibetan leaders during...   
2      Some scholars note that Tibetan leaders during...   
3      Some scholars note that Tibetan leaders during...   
4      Some scholars note that Tibetan leaders during...   
...                                                  ...   
69864  In contrast, Botswana has recently been forced...   
69865  In contrast, Botswana has recently been forced...   
69866  In contrast, Botswana has recently been forced...   
69867  In contrast, Botswana has recently been forced...   
69868  In contrast, Botswana has recently been forced...   

                            answer answer_start answer_end  
0      [Mainland Chinese scholars]        [274]      [299]  
1                    [horse trade]        [338]      [349]  
2                      [1402–1424]        [739]      [748]  
3                  [Deshin Shekpa]        [821]      [834]  
4         [the Karma Kagyu school]        [863]      [885]  
...                            ...          ...        ...  
69864         [ban trophy hunting]         [50]       [68]  
69865                   [antelope]        [126]      [134]  
69866               [hippopotamus]        [251]      [263]  
69867                   [elephant]        [214]      [222]  
69868                   [poaching]        [404]      [412]  

[69869 rows x 8 columns]

In [355]:
standard_dm.val_df

question_id  \
0      56be85543aeaaa14008c9063   
1      56be85543aeaaa14008c9065   
2      56be85543aeaaa14008c9066   
3      56be86cf3aeaaa14008c9076   
4      56be86cf3aeaaa14008c9078   
...                         ...   
17282  573445bbacc1501500babd6d   
17283  573445bbacc1501500babd6e   
17284  573445bbacc1501500babd6f   
17285  573445bbacc1501500babd70   
17286  573445bbacc1501500babd71   

                                                question            title  \
0               When did Beyonce start becoming popular?          Beyoncé   
1      What areas did Beyonce compete in when she was...          Beyoncé   
2      When did Beyonce leave Destiny's Child and bec...          Beyoncé   
3      After her second solo album, what other entert...          Beyoncé   
4                        Which artist did Beyonce marry?          Beyoncé   
...                                                  ...              ...   
17282                  Why is cycling popular in Tucson?  Tucson,_Arizona   
17283                                  What is The Loop?  Tucson,_Arizona   
17284          How many miles of trails are in The Loop?  Tucson,_Arizona   
17285  What organization advises the Tucson governmen...  Tucson,_Arizona   
17286  What kind of places to ride bikes does Tucson ...  Tucson,_Arizona   

       context_id                                            context  \
0              55  Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...   
1              55  Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...   
2              55  Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...   
3              56  Following the disbandment of Destiny's Child i...   
4              56  Following the disbandment of Destiny's Child i...   
...           ...                                                ...   
17282       16649  Cycling is popular in Tucson due to its flat t...   
17283       16649  Cycling is popular in Tucson due to its flat t...   
17284       16649  Cycling is popular in Tucson due to its flat t...   
17285       16649  Cycling is popular in Tucson due to its flat t...   
17286       16649  Cycling is popular in Tucson due to its flat t...   

                                                  answer answer_start  \
0                                    [in the late 1990s]        [269]   
1                                  [singing and dancing]        [207]   
2                                                 [2003]        [526]   
3                                               [acting]        [207]   
4                                                [Jay Z]        [369]   
...                                                  ...          ...   
17282                 [its flat terrain and dry climate]         [36]   
17283                  [a network of seven linear parks]        [254]   
17284                                         [over 100]        [297]   
17285    [Tucson-Pima County Bicycle Advisory Committee]        [429]   
17286  [marked bike routes, signal crossings, on-stre...        [126]   

      answer_end  
0          [286]  
1          [226]  
2          [530]  
3          [213]  
4          [374]  
...          ...  
17282       [68]  
17283      [285]  
17284      [305]  
17285      [474]  
17286      [240]  

[17287 rows x 8 columns]

In [356]:
standard_dm.test_df

question_id  \
0      56be4db0acb8001400a502ec   
1      56be4db0acb8001400a502ed   
2      56be4db0acb8001400a502ee   
3      56be4db0acb8001400a502ef   
4      56be4db0acb8001400a502f0   
...                         ...   
10525  5737aafd1c456719005744fb   
10526  5737aafd1c456719005744fc   
10527  5737aafd1c456719005744fd   
10528  5737aafd1c456719005744fe   
10529  5737aafd1c456719005744ff   

                                                question          title  \
0      Which NFL team represented the AFC at Super Bo...  Super_Bowl_50   
1      Which NFL team represented the NFC at Super Bo...  Super_Bowl_50   
2                    Where did Super Bowl 50 take place?  Super_Bowl_50   
3                      Which NFL team won Super Bowl 50?  Super_Bowl_50   
4      What color was used to emphasize the 50th anni...  Super_Bowl_50   
...                                                  ...            ...   
10525  What is the metric term less used than the New...          Force   
10526  What is the kilogram-force sometimes reffered ...          Force   
10527  What is a very seldom used unit of mass in the...          Force   
10528  What seldom used term of a unit of force equal...          Force   
10529  What is the seldom used force unit equal to on...          Force   

       context_id                                            context  \
0               0  Super Bowl 50 was an American football game to...   
1               0  Super Bowl 50 was an American football game to...   
2               0  Super Bowl 50 was an American football game to...   
3               0  Super Bowl 50 was an American football game to...   
4               0  Super Bowl 50 was an American football game to...   
...           ...                                                ...   
10525        2066  The pound-force has a metric counterpart, less...   
10526        2066  The pound-force has a metric counterpart, less...   
10527        2066  The pound-force has a metric counterpart, less...   
10528        2066  The pound-force has a metric counterpart, less...   
10529        2066  The pound-force has a metric counterpart, less...   

                                                  answer     answer_start  \
0                                       [Denver Broncos]            [177]   
1                                    [Carolina Panthers]            [249]   
2      [Santa Clara, California, Levi's Stadium, Levi...  [403, 355, 355]   
3                                       [Denver Broncos]            [177]   
4                                                 [gold]            [521]   
...                                                  ...              ...   
10525  [kilogram-force, pound-force, kilogram-force (...  [82, 4, 82, 78]   
10526                                         [kilopond]            [114]   
10527               [slug, metric slug, the metric slug]  [274, 267, 263]   
10528                                              [kip]            [712]   
10529                                           [sthène]            [665]   

              answer_end  
0                  [191]  
1                  [266]  
2        [426, 369, 427]  
3                  [191]  
4                  [525]  
...                  ...  
10525  [96, 15, 102, 98]  
10526              [122]  
10527    [278, 278, 278]  
10528              [715]  
10529              [671]  

[10530 rows x 8 columns]

## Baseline model

In [473]:
baseline_model = model.QABaselineModel(glove_embedding_layer, MAX_CONTEXT_TOKENS)
baseline_model.count_parameters()

101400

In [474]:
baseline_args = transformers.TrainingArguments(
    output_dir="./checkpoints",
    logging_dir="./runs",
    logging_first_step=True,
    logging_steps=5,
    overwrite_output_dir=True,
    evaluation_strategy="epoch",
    learning_rate=1e-3,
    num_train_epochs=10,
    remove_unused_columns=False,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=64,
    label_names=["answers"],
)

In [475]:
baseline_trainer = training.SquadTrainer(
    model=baseline_model,
    args=baseline_args,
    data_collator=standard_dm.tokenizer,
    train_dataset=standard_dm.train_dataset,
    eval_dataset=standard_dm.val_dataset,
    compute_metrics=training.compute_metrics,
)

In [85]:
baseline_run_name = utils.get_run_name()
baseline_wandb_logger = init_wandb(
    name=baseline_run_name, group="baseline", reinit=True,
)

In [476]:
baseline_trainer.train()

./checkpoints
tensor([[-4.3361, -4.4625, -4.3812,  ...,  0.0000,  0.0000,  0.0000],
        [-4.3238, -4.4702, -4.3845,  ...,  0.0000,  0.0000,  0.0000],
        [-4.4277, -4.4621, -4.4277,  ...,  0.0000,  0.0000,  0.0000],
        [-4.3350, -4.4268, -4.3731,  ...,  0.0000,  0.0000,  0.0000]],
       grad_fn=<IndexPutBackward>) tensor([[-4.8803, -5.0429, -5.0429,  ...,  0.0000,  0.0000,  0.0000],
        [-4.4435, -4.6393, -4.4349,  ...,  0.0000,  0.0000,  0.0000],
        [-4.8729, -4.9180, -4.6894,  ...,  0.0000,  0.0000,  0.0000],
        [-4.6571, -4.6995, -4.4812,  ...,  0.0000,  0.0000,  0.0000]],
       grad_fn=<IndexPutBackward>)
tensor([0.1591, 0.1591, 0.1591, 0.1591], grad_fn=<DivBackward0>) tensor([0.1242, 0.1951, 0.1471, 0.1838], grad_fn=<DivBackward0>) tensor(1.2865, grad_fn=<SumBackward0>)


tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], grad_fn=<IndexPutBackward>) tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], grad_fn=<IndexPutBackward>)
tensor([nan, nan, nan, nan], grad_fn=<DivBackward0>) tensor([nan, nan, nan, nan], grad_fn=<DivBackward0>) tensor(nan, grad_fn=<SumBackward0>)


AssertionError: 

In [87]:
baseline_wandb_logger.finish()

## BiDAF

In [477]:
bidaf_model = model.BiDAFModel(glove_embedding_layer)
bidaf_model.count_parameters()

314350

In [478]:
bidaf_args = transformers.TrainingArguments(
    output_dir="./checkpoints",
    logging_dir="./runs",
    logging_first_step=True,
    logging_steps=5,
    overwrite_output_dir=True,
    evaluation_strategy="epoch",
    learning_rate=1e-3,
    num_train_epochs=10,
    remove_unused_columns=False,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=64,
    label_names=["answers"]
)

In [479]:
bidaf_optimizer = optim.Adadelta(bidaf_model.parameters(), lr=0.5)
bidaf_lr_scheduler = optim.lr_scheduler.ExponentialLR(bidaf_optimizer, gamma=.999)

In [480]:
bidaf_trainer = training.SquadTrainer(
    model=bidaf_model,
    args=bidaf_args,
    data_collator=standard_dm.tokenizer,
    train_dataset=standard_dm.train_dataset,
    eval_dataset=standard_dm.val_dataset,
    optimizers=(bidaf_optimizer, bidaf_lr_scheduler),
    compute_metrics=training.compute_metrics,
)

In [148]:
bidaf_run_name = utils.get_run_name()
bidaf_wandb_logger = init_wandb(name=bidaf_run_name, group="bidaf", reinit=True,)

wandb: wandb version 0.10.14 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade


In [481]:
bidaf_trainer.train()

./checkpoints
tensor([[-4.4330, -4.4352, -4.4454,  ...,  0.0000,  0.0000,  0.0000],
        [-3.9968, -4.0153, -4.0168,  ...,  0.0000,  0.0000,  0.0000],
        [-4.6983, -4.6966, -4.7108,  ...,  0.0000,  0.0000,  0.0000],
        [-4.3045, -4.2952, -4.3123,  ...,  0.0000,  0.0000,  0.0000]],
       grad_fn=<IndexPutBackward>) tensor([[-5.0482, -5.0245, -5.0189,  ...,  0.0000,  0.0000,  0.0000],
        [-4.6292, -4.5821, -4.5835,  ...,  0.0000,  0.0000,  0.0000],
        [-4.8629, -4.8904, -4.8862,  ...,  0.0000,  0.0000,  0.0000],
        [-4.6440, -4.6583, -4.6655,  ...,  0.0000,  0.0000,  0.0000]],
       grad_fn=<IndexPutBackward>)
tensor([0.1531, 0.2365, 0.1183, 0.1758], grad_fn=<DivBackward0>) tensor([0.1237, 0.1944, 0.1466, 0.1832], grad_fn=<DivBackward0>) tensor(1.3316, grad_fn=<SumBackward0>)


tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], grad_fn=<IndexPutBackward>) tensor([[nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan],
        [nan, nan, nan,  ..., nan, nan, nan]], grad_fn=<IndexPutBackward>)
tensor([nan, nan, nan, nan], grad_fn=<DivBackward0>) tensor([nan, nan, nan, nan], grad_fn=<DivBackward0>) tensor(nan, grad_fn=<SumBackward0>)


AssertionError: 

In [200]:
bidaf_wandb_logger.finish()

## BERT

In [ ]:
bert_tokenizer = BertWordPieceTokenizer("data/bert-base-uncased-vocab.txt", lowercase=True)
bert_tokenizer.enable_padding(
    direction="right",
    pad_type_id=1,
    pad_token=PAD_TOKEN,
)

In [ ]:
bert_tokenizer = dataset.BertSquadTokenizer(bert_tokenizer)

In [ ]:
bert_dm = dataset.SquadDataManager(squad_dataset, bert_tokenizer)

In [216]:
bert_model = transformers.BertModel.from_pretrained("bert-base-uncased")

In [58]:
bert_args = transformers.TrainingArguments(
    output_dir="./checkpoints",
    logging_dir="./runs",
    logging_first_step=True,
    logging_steps=5,
    overwrite_output_dir=True,
    evaluation_strategy="epoch",
    learning_rate=1e-3,
    num_train_epochs=10,
    remove_unused_columns=False,
    per_device_train_batch_size=256,
    per_device_eval_batch_size=64,
    label_names=["answers"]
)

In [ ]:
bert_trainer = training.SquadTrainer(
    model=bert_model,
    args=bert_args,
    data_collator=bert_dm.tokenizer,
    train_dataset=bert_dm.train_dataset,
    eval_dataset=bert_dm.val_dataset,
    compute_metrics=training.compute_metrics,
)

In [ ]:
bert_run_name = utils.get_run_name()
bert_wandb_logger = init_wandb(name=bert_run_name, group="bert", reinit=True,)

In [288]:
bert_trainer.train()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])


KeyError: 'loss'

In [ ]:
bert_wandb_logger.finish()