# Question answering on the SQuAD dataset

In [38]:
import sys
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
import wandb
import transformers

import dataset
import model

%load_ext autoreload
%autoreload 2
%matplotlib inline

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [2]:
plt.rcParams['figure.figsize'] = [8, 6]
plt.rcParams['figure.dpi'] = 100
plt.rcParams['axes.xmargin'] = .05
plt.rcParams['axes.ymargin'] = .05
plt.style.use('ggplot')

%env WANDB_WATCH=all
%env WANDB_PROJECT=squad-qa
%env WANDB_DISABLED=false

env: WANDB_WATCH=all
env: WANDB_PROJECT=squad-qa
env: WANDB_DISABLED=false


In [54]:
!{sys.executable} -m wandb login

wandb: Currently logged in as: wadaboa (use `wandb login --relogin` to force relogin)


## Data loading/preparation

In [4]:
def preprocess_question(text):
    """
    Preprocess the given question text from the SQuAD dataset
    """
    return text.lower()


def preprocess_context(text):
    """
    Preprocess the given context text from the SQuAD dataset
    """
    return text.lower()

In [5]:
squad_dataset = dataset.SquadDataset(
    question_preprocessor=preprocess_question,
    context_preprocessor=preprocess_context,
)
squad_dataset.dataframe

index  \
0      5733be284776f41900661182   
1      5733be284776f4190066117f   
2      5733be284776f41900661180   
3      5733be284776f41900661181   
4      5733be284776f4190066117e   
...                         ...   
87594  5735d259012e2f140011a09d   
87595  5735d259012e2f140011a09e   
87596  5735d259012e2f140011a09f   
87597  5735d259012e2f140011a0a0   
87598  5735d259012e2f140011a0a1   

                                                question  \
0      To whom did the Virgin Mary allegedly appear i...   
1      What is in front of the Notre Dame Main Building?   
2      The Basilica of the Sacred heart at Notre Dame...   
3                      What is the Grotto at Notre Dame?   
4      What sits on top of the Main Building at Notre...   
...                                                  ...   
87594  In what US state did Kathmandu first establish...   
87595               What was Yangon previously known as?   
87596  With what Belorussian city does Kathmandu have...   
87597  In what year did Kathmandu create its initial ...   
87598                      What is KMC an initialism of?   

                          title  context_id  \
0      University_of_Notre_Dame           0   
1      University_of_Notre_Dame           0   
2      University_of_Notre_Dame           0   
3      University_of_Notre_Dame           0   
4      University_of_Notre_Dame           0   
...                         ...         ...   
87594                 Kathmandu       18890   
87595                 Kathmandu       18890   
87596                 Kathmandu       18890   
87597                 Kathmandu       18890   
87598                 Kathmandu       18890   

                                                 context  \
0      Architecturally, the school has a Catholic cha...   
1      Architecturally, the school has a Catholic cha...   
2      Architecturally, the school has a Catholic cha...   
3      Architecturally, the school has a Catholic cha...   
4      Architecturally, the school has a Catholic cha...   
...                                                  ...   
87594  Kathmandu Metropolitan City (KMC), in order to...   
87595  Kathmandu Metropolitan City (KMC), in order to...   
87596  Kathmandu Metropolitan City (KMC), in order to...   
87597  Kathmandu Metropolitan City (KMC), in order to...   
87598  Kathmandu Metropolitan City (KMC), in order to...   

                                        answer  answer_start  answer_end  
0                   Saint Bernadette Soubirous           515         541  
1                    a copper statue of Christ           188         213  
2                            the Main Building           279         296  
3      a Marian place of prayer and reflection           381         420  
4           a golden statue of the Virgin Mary            92         126  
...                                        ...           ...         ...  
87594                                   Oregon           229         235  
87595                                  Rangoon           414         421  
87596                                    Minsk           476         481  
87597                                     1975           199         203  
87598              Kathmandu Metropolitan City             0          27  

[87599 rows x 8 columns]

In [6]:
squad_dataset.train_df

index  \
0      5733be284776f41900661182   
1      5733be284776f4190066117f   
2      5733be284776f41900661180   
3      5733be284776f41900661181   
4      5733be284776f4190066117e   
...                         ...   
70185  5735d259012e2f140011a09d   
70186  5735d259012e2f140011a09e   
70187  5735d259012e2f140011a09f   
70188  5735d259012e2f140011a0a0   
70189  5735d259012e2f140011a0a1   

                                                question  \
0      To whom did the Virgin Mary allegedly appear i...   
1      What is in front of the Notre Dame Main Building?   
2      The Basilica of the Sacred heart at Notre Dame...   
3                      What is the Grotto at Notre Dame?   
4      What sits on top of the Main Building at Notre...   
...                                                  ...   
70185  In what US state did Kathmandu first establish...   
70186               What was Yangon previously known as?   
70187  With what Belorussian city does Kathmandu have...   
70188  In what year did Kathmandu create its initial ...   
70189                      What is KMC an initialism of?   

                          title  context_id  \
0      University_of_Notre_Dame           0   
1      University_of_Notre_Dame           0   
2      University_of_Notre_Dame           0   
3      University_of_Notre_Dame           0   
4      University_of_Notre_Dame           0   
...                         ...         ...   
70185                 Kathmandu       18890   
70186                 Kathmandu       18890   
70187                 Kathmandu       18890   
70188                 Kathmandu       18890   
70189                 Kathmandu       18890   

                                                 context  \
0      Architecturally, the school has a Catholic cha...   
1      Architecturally, the school has a Catholic cha...   
2      Architecturally, the school has a Catholic cha...   
3      Architecturally, the school has a Catholic cha...   
4      Architecturally, the school has a Catholic cha...   
...                                                  ...   
70185  Kathmandu Metropolitan City (KMC), in order to...   
70186  Kathmandu Metropolitan City (KMC), in order to...   
70187  Kathmandu Metropolitan City (KMC), in order to...   
70188  Kathmandu Metropolitan City (KMC), in order to...   
70189  Kathmandu Metropolitan City (KMC), in order to...   

                                        answer  answer_start  answer_end  
0                   Saint Bernadette Soubirous           515         541  
1                    a copper statue of Christ           188         213  
2                            the Main Building           279         296  
3      a Marian place of prayer and reflection           381         420  
4           a golden statue of the Virgin Mary            92         126  
...                                        ...           ...         ...  
70185                                   Oregon           229         235  
70186                                  Rangoon           414         421  
70187                                    Minsk           476         481  
70188                                     1975           199         203  
70189              Kathmandu Metropolitan City             0          27  

[70190 rows x 8 columns]

In [7]:
squad_dataset.val_df

index  \
0      56be85543aeaaa14008c9063   
1      56be85543aeaaa14008c9065   
2      56be85543aeaaa14008c9066   
3      56bf6b0f3aeaaa14008c9601   
4      56bf6b0f3aeaaa14008c9602   
...                         ...   
17404  5732868bb3a91d1900202e0f   
17405  5732868bb3a91d1900202e10   
17406  5732868bb3a91d1900202e11   
17407  5732868bb3a91d1900202e12   
17408  5732868bb3a91d1900202e13   

                                                question  \
0               When did Beyonce start becoming popular?   
1      What areas did Beyonce compete in when she was...   
2      When did Beyonce leave Destiny's Child and bec...   
3          In what city and state did Beyonce  grow up?    
4             In which decade did Beyonce become famous?   
...                                                  ...   
17404  At what Augusta hole was the Eisenhower Pine l...   
17405  How many meters away from the Masters tee on A...   
17406  What did Eisenhower want to be done to the Eis...   
17407  What damaged the Eisenhower Pine in February 2...   
17408  In what year did Eisenhower propose that the p...   

                      title  context_id  \
0                   Beyoncé          55   
1                   Beyoncé          55   
2                   Beyoncé          55   
3                   Beyoncé          55   
4                   Beyoncé          55   
...                     ...         ...   
17404  Dwight_D._Eisenhower       18592   
17405  Dwight_D._Eisenhower       18592   
17406  Dwight_D._Eisenhower       18592   
17407  Dwight_D._Eisenhower       18592   
17408  Dwight_D._Eisenhower       18592   

                                                 context               answer  \
0      Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...    in the late 1990s   
1      Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...  singing and dancing   
2      Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...                 2003   
3      Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...       Houston, Texas   
4      Beyoncé Giselle Knowles-Carter (/biːˈjɒnseɪ/ b...           late 1990s   
...                                                  ...                  ...   
17404  A loblolly pine, known as the "Eisenhower Pine...                 17th   
17405  A loblolly pine, known as the "Eisenhower Pine...                  192   
17406  A loblolly pine, known as the "Eisenhower Pine...             cut down   
17407  A loblolly pine, known as the "Eisenhower Pine...            ice storm   
17408  A loblolly pine, known as the "Eisenhower Pine...                 1956   

       answer_start  answer_end  
0               269         286  
1               207         226  
2               526         530  
3               166         180  
4               276         286  
...             ...         ...  
17404            74          78  
17405           110         113  
17406           279         287  
17407           478         487  
17408           237         241  

[17409 rows x 8 columns]

In [8]:
squad_dataset.train_dataset[0]

('To whom did the Virgin Mary allegedly appear in 1858 in Lourdes France?',
 'Architecturally, the school has a Catholic character. Atop the Main Building\'s gold dome is a golden statue of the Virgin Mary. Immediately in front of the Main Building and facing it, is a copper statue of Christ with arms upraised with the legend "Venite Ad Me Omnes". Next to the Main Building is the Basilica of the Sacred Heart. Immediately behind the basilica is the Grotto, a Marian place of prayer and reflection. It is a replica of the grotto at Lourdes, France where the Virgin Mary reputedly appeared to Saint Bernadette Soubirous in 1858. At the end of the main drive (and in a direct line that connects through 3 statues and the Gold Dome), is a simple, modern stone statue of Mary.',
 515,
 541)

## Baseline

In [9]:
UNK_TOKEN = "[UNK]"
PAD_TOKEN = "[PAD]"

In [10]:
import gensim
import gensim.downloader as gloader


def load_embedding_model(model_type, embedding_dimension=50):
    """
    Loads a pre-trained word embedding model via gensim library
    """
    # Find the correct embedding model name
    download_path = ""
    if model_type.strip().lower() == "word2vec":
        download_path = "word2vec-google-news-300"
    elif model_type.strip().lower() == "glove":
        download_path = f"glove-wiki-gigaword-{embedding_dimension}"
    else:
        raise AttributeError(
            "Unsupported embedding model type (choose from {word2vec, glove})"
        )

    # Check download
    try:
        emb_model = gloader.load(download_path)
    except ValueError as e:
        print("Invalid embedding model name. Check the embedding dimension:")
        print("Word2Vec: {300}")
        print("GloVe: {50, 100, 200, 300}")
        raise e

    return emb_model


glove_embedding_dimension = 50
glove_embedding_model = load_embedding_model("glove", embedding_dimension=glove_embedding_dimension)

In [11]:
glove_unk = np.mean(glove_embedding_model.vectors, axis=0)
glove_unk

array([-0.12920076, -0.28866628, -0.01224866, -0.05676644, -0.20210965,
       -0.08389011,  0.33359843,  0.16045167,  0.03867431,  0.17833012,
        0.04696583, -0.00285802,  0.29099807,  0.04613704, -0.20923874,
       -0.06613114, -0.06822549,  0.07665912,  0.3134014 ,  0.17848536,
       -0.1225775 , -0.09916984, -0.07495987,  0.06413227,  0.14441176,
        0.60894334,  0.17463093,  0.05335403, -0.01273871,  0.03474107,
       -0.8123879 , -0.04688699,  0.20193407,  0.2031118 , -0.03935686,
        0.06967544, -0.01553638, -0.03405238, -0.06528071,  0.12250231,
        0.13991883, -0.17446303, -0.08011883,  0.0849521 , -0.01041659,
       -0.13705009,  0.20127155,  0.10069408,  0.00653003,  0.01685157],
      dtype=float32)

In [12]:
any(np.all(glove_embedding_model.vectors == 0, axis=1))

False

In [13]:
glove_embedding_model.add(UNK_TOKEN, glove_unk)
glove_embedding_model.add(PAD_TOKEN, np.zeros((1, glove_embedding_dimension)))

In [14]:
glove_embedding_model.vectors.shape

(400002, 50)

In [15]:
glove_embedding_model[UNK_TOKEN]

array([-0.12920076, -0.28866628, -0.01224866, -0.05676644, -0.20210965,
       -0.08389011,  0.33359843,  0.16045167,  0.03867431,  0.17833012,
        0.04696583, -0.00285802,  0.29099807,  0.04613704, -0.20923874,
       -0.06613114, -0.06822549,  0.07665912,  0.3134014 ,  0.17848536,
       -0.1225775 , -0.09916984, -0.07495987,  0.06413227,  0.14441176,
        0.60894334,  0.17463093,  0.05335403, -0.01273871,  0.03474107,
       -0.8123879 , -0.04688699,  0.20193407,  0.2031118 , -0.03935686,
        0.06967544, -0.01553638, -0.03405238, -0.06528071,  0.12250231,
        0.13991883, -0.17446303, -0.08011883,  0.0849521 , -0.01041659,
       -0.13705009,  0.20127155,  0.10069408,  0.00653003,  0.01685157],
      dtype=float32)

In [16]:
glove_embedding_model[PAD_TOKEN]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)

In [17]:
list(glove_embedding_model.vocab.keys())[-1]

'[PAD]'

In [18]:
glove_vocab = dict(
    zip(glove_embedding_model.index2word, range(len(glove_embedding_model.index2word)))
)

In [19]:
glove_embedding_layer = nn.Embedding(
    glove_embedding_model.vectors.shape[0],
    glove_embedding_dimension,
    padding_idx=glove_vocab[PAD_TOKEN],
)
glove_embedding_layer.weight = nn.Parameter(
    torch.from_numpy(glove_embedding_model.vectors)
)
glove_embedding_layer.weight.requires_grad = False

In [20]:
MAX_QUESTION_TOKENS = 25
MAX_CONTEXT_TOKENS = 300

In [21]:
import tokenizers
from tokenizers import Tokenizer
from tokenizers.models import WordLevel
from tokenizers.normalizers import Sequence, StripAccents, Lowercase, Strip
from tokenizers.pre_tokenizers import Whitespace

baseline_question_tokenizer = Tokenizer(WordLevel(glove_vocab, unk_token=UNK_TOKEN))
baseline_question_tokenizer.normalizer = Sequence([StripAccents(), Lowercase(), Strip()])
baseline_question_tokenizer.pre_tokenizer = Whitespace()
baseline_question_tokenizer.enable_padding(
    direction="right",
    pad_id=glove_vocab[PAD_TOKEN],
    pad_type_id=1,
    pad_token=PAD_TOKEN,
    length=MAX_QUESTION_TOKENS,
)
baseline_question_tokenizer.enable_truncation(MAX_QUESTION_TOKENS)

baseline_context_tokenizer = Tokenizer(WordLevel(glove_vocab, unk_token=UNK_TOKEN))
baseline_context_tokenizer.normalizer = Sequence([StripAccents(), Lowercase(), Strip()])
baseline_context_tokenizer.pre_tokenizer = Whitespace()
baseline_context_tokenizer.enable_padding(
    direction="right",
    pad_id=glove_vocab[PAD_TOKEN],
    pad_type_id=1,
    pad_token=PAD_TOKEN,
    length=MAX_CONTEXT_TOKENS,
)
baseline_context_tokenizer.enable_truncation(MAX_CONTEXT_TOKENS)

In [22]:
baseline_question_tokenizer.encode_batch([("ciao ciao", "miajjjo miao"), ("pmc", "mdmd")])[0].attention_mask

[1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [82]:
cont=torch.randint(10, (2,5,4))
ques=torch.randint(10, (2,2,4))
out = torch.zeros((2, 5, 2, 12))
for i in range(ques.shape[0]):
    for j in range(cont.shape[1]):
        for k in range(ques.shape[1]):
            out[i, j, k] = torch.cat([cont[i, j], ques[i, k], cont[i, j] * ques[i, k]])
print(cont)
print(ques)
print(out.reshape(2,10,12))

tensor([[[8, 5, 7, 7],
         [0, 8, 5, 7],
         [3, 3, 0, 5],
         [5, 1, 4, 6],
         [9, 4, 8, 2]],

        [[9, 8, 3, 4],
         [0, 9, 1, 8],
         [0, 9, 6, 1],
         [3, 9, 8, 6],
         [7, 8, 7, 6]]])
tensor([[[8, 4, 8, 5],
         [0, 1, 0, 9]],

        [[2, 7, 6, 3],
         [6, 4, 8, 9]]])
tensor([[[ 8.,  5.,  7.,  7.,  8.,  4.,  8.,  5., 64., 20., 56., 35.],
         [ 8.,  5.,  7.,  7.,  0.,  1.,  0.,  9.,  0.,  5.,  0., 63.],
         [ 0.,  8.,  5.,  7.,  8.,  4.,  8.,  5.,  0., 32., 40., 35.],
         [ 0.,  8.,  5.,  7.,  0.,  1.,  0.,  9.,  0.,  8.,  0., 63.],
         [ 3.,  3.,  0.,  5.,  8.,  4.,  8.,  5., 24., 12.,  0., 25.],
         [ 3.,  3.,  0.,  5.,  0.,  1.,  0.,  9.,  0.,  3.,  0., 45.],
         [ 5.,  1.,  4.,  6.,  8.,  4.,  8.,  5., 40.,  4., 32., 30.],
         [ 5.,  1.,  4.,  6.,  0.,  1.,  0.,  9.,  0.,  1.,  0., 54.],
         [ 9.,  4.,  8.,  2.,  8.,  4.,  8.,  5., 72., 16., 64., 10.],
         [ 9.,  4.,  8.,  2.,  

In [101]:
torch.einsum('bcd, bqd->bcqd', cont, ques).reshape(2,10,4)

tensor([[[64, 20, 56, 35],
         [ 0,  5,  0, 63],
         [ 0, 32, 40, 35],
         [ 0,  8,  0, 63],
         [24, 12,  0, 25],
         [ 0,  3,  0, 45],
         [40,  4, 32, 30],
         [ 0,  1,  0, 54],
         [72, 16, 64, 10],
         [ 0,  4,  0, 18]],

        [[18, 56, 18, 12],
         [54, 32, 24, 36],
         [ 0, 63,  6, 24],
         [ 0, 36,  8, 72],
         [ 0, 63, 36,  3],
         [ 0, 36, 48,  9],
         [ 6, 63, 48, 18],
         [18, 36, 64, 54],
         [14, 56, 42, 18],
         [42, 32, 56, 54]]])

In [28]:
class BaselineDataCollatorWithPadding:
    """
    Data collator that will dynamically pad the inputs received
    """

    def __init__(self, question_tokenizer, context_tokenizer):
        self.question_tokenizer = question_tokenizer
        self.context_tokenizer = context_tokenizer

    def find_tokenized_answer_indexes(self, offsets, query, dim):
        index = torch.nonzero(offsets[:, dim] == query)
        assert len(index) in (0, 1)
        return index.item() if len(index) > 0 else -1

    def __call__(self, inputs):
        (questions, contexts, answers_start, answers_end) = zip(*inputs)
        tokenized_questions = self.question_tokenizer.encode_batch(questions)
        tokenized_contexts = self.context_tokenizer.encode_batch(contexts)
        batch_size = len(tokenized_questions)
        questions_shape = (batch_size, len(tokenized_questions[0].ids))
        contexts_shape = (batch_size, len(tokenized_contexts[0].ids))

        batch = {
            "question_ids": torch.empty(questions_shape, dtype=torch.long),
            "question_type_ids": torch.empty(questions_shape, dtype=torch.long),
            "question_attention_mask": torch.empty(questions_shape, dtype=torch.bool),
            "question_special_tokens_mask": torch.empty(
                questions_shape, dtype=torch.bool
            ),
            "question_lenghts": torch.empty((batch_size,), dtype=torch.long),
            "context_ids": torch.empty(contexts_shape, dtype=torch.long),
            "context_type_ids": torch.empty(contexts_shape, dtype=torch.long),
            "context_attention_mask": torch.empty(contexts_shape, dtype=torch.bool),
            "context_special_tokens_mask": torch.empty(
                contexts_shape, dtype=torch.bool
            ),
            "context_offsets": torch.empty((*contexts_shape, 2), dtype=torch.long),
            "context_lenghts": torch.empty((batch_size,), dtype=torch.long),
            # "answer_start": torch.tensor(answers_start, dtype=torch.long),
            # "answer_end": torch.tensor(answers_end, dtype=torch.long),
            "answer_start": torch.empty((batch_size,), dtype=torch.long),
            "answer_end": torch.empty((batch_size,), dtype=torch.long),
        }
        for i in range(batch_size):
            batch["question_ids"][i] = torch.tensor(tokenized_questions[i].ids)
            batch["question_type_ids"][i] = torch.tensor(
                tokenized_questions[i].type_ids
            )
            batch["question_attention_mask"][i] = torch.tensor(
                tokenized_questions[i].attention_mask
            )
            batch["question_special_tokens_mask"][i] = torch.tensor(
                tokenized_questions[i].special_tokens_mask
            )
            batch["question_lenghts"][i] = torch.count_nonzero(
                ~batch["question_special_tokens_mask"][i]
            )
            batch["context_ids"][i] = torch.tensor(tokenized_contexts[i].ids)
            batch["context_type_ids"][i] = torch.tensor(tokenized_contexts[i].type_ids)
            batch["context_attention_mask"][i] = torch.tensor(
                tokenized_contexts[i].attention_mask
            )
            batch["context_special_tokens_mask"][i] = torch.tensor(
                tokenized_contexts[i].special_tokens_mask
            )
            batch["context_offsets"][i] = torch.tensor(tokenized_contexts[i].offsets)
            batch["context_lenghts"][i] = torch.count_nonzero(
                ~batch["context_special_tokens_mask"][i]
            )
            masked_offsets = batch["context_offsets"][i][batch["context_attention_mask"][i]]
            batch["answer_start"][i] = self.find_tokenized_answer_indexes(
                masked_offsets, answers_start[i], 0
            )
            batch["answer_end"][i] = self.find_tokenized_answer_indexes(
                masked_offsets, answers_end[i], 1
            )

        return batch

In [29]:
baseline_model = model.QABaselineModel(glove_embedding_layer, MAX_CONTEXT_TOKENS)
baseline_model.count_parameters()

101400

In [61]:
baseline_args = transformers.TrainingArguments(
    output_dir="./checkpoints",
    logging_dir="./runs",
    overwrite_output_dir=True,
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    num_train_epochs=3,
    remove_unused_columns=False,
    per_device_train_batch_size=64,
    per_device_eval_batch_size=64,
    label_names=["answer_start", "answer_end"]
)

In [62]:
baseline_trainer = transformers.Trainer(
    model=baseline_model,
    args=baseline_args,
    data_collator=BaselineDataCollatorWithPadding(baseline_question_tokenizer, baseline_context_tokenizer),
    train_dataset=squad_dataset.train_dataset,
    eval_dataset=squad_dataset.val_dataset,
    #callbacks=[transformers.integrations.WandbCallback]
)

AssertionError: WandbCallback requires wandb to be installed. Run `pip install wandb`.

In [63]:
baseline_trainer.train()

KeyboardInterrupt: 

## BERT

In [277]:
tokenizer = transformers.BertTokenizer.from_pretrained("bert-base-uncased")
model = transformers.BertModel.from_pretrained("bert-base-uncased")

In [58]:
args = transformers.TrainingArguments(
    output_dir="./checkpoints",
    logging_dir="./runs",
    overwrite_output_dir=True,
    evaluation_strategy="epoch",
    learning_rate=2e-5,
    num_train_epochs=3,
    remove_unused_columns=False,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    label_names=["answer_start", "answer_end"],
)

In [59]:
class DataCollatorWithPadding:
    """
    Data collator that will dynamically pad the inputs received
    """

    def __init__(self, tokenizer, padding=True, max_lenght=None):
        self.tokenizer = tokenizer
        self.padding = True
        self.max_length = None

    def __call__(self, inputs):
        (questions, contexts, _, _) = zip(*inputs)
        tokenized = self.tokenizer(questions, contexts)
        batch = self.tokenizer.pad(
            tokenized,
            padding=self.padding,
            max_length=self.max_length,
            return_tensors="pt",
        )
        return batch

In [60]:
data_collator = DataCollatorWithPadding(tokenizer)

NameError: name 'tokenizer' is not defined

In [ ]:
trainer = transformers.Trainer(
    model=model,
    args=args,
    data_collator=data_collator,
    train_dataset=squad_dataset.train_dataset,
    eval_dataset=squad_dataset.val_dataset
)

In [288]:
trainer.train()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])


KeyError: 'loss'